(() => {
  'use strict';
  const latin={"series": "Súwret tariyxı · 03", "title": "Andromeda", "lead": "Galaktika kórinis aladı. FITS kórinisi menen tayar Andromeda súwretin salıstırıń.", "before": "FITS kórinisi", "after": "Tayar súwret", "slider": "Óńlew nátiyjelerin salıstırıw", "help": "Hár bir nusqanı kóriw ushın jıljıtqıshtı yamasa baǵdar túymelerin paydalanıń.", "caption": "Ázzi detallardı kórsetiw ushın FITS kórinisiniń jarqınlıǵı sozılǵan. Bul kameradan alınǵan óńlenbegen kadr emes. Tayar súwret — fotograf usınǵan JPEG faylı.", "open": "Tayar súwretti ashıw", "openBefore": "FITS kórinisin ashıw", "capture": "Súwret haqqında", "heading": "Galaktikanı ashıw.", "story": "Andromeda súwretim FITS faylınıń kórinisi menen birge berilgen. Eki nusqadaǵı shań jolaqların salıstırıp, óńlew detallardı qalay kórsetetuǵının kóriń.", "process": "FITS kórinisinde úsh reń kanalına birdey jarqınlıq sozıwı qollanılǵan. Tayar súwret — galeriyadaǵı fotosúwretim.", "learning": "Úyreniwden bir estelik: bir juldızlar maydanı, jolımızdıń eki basqıshında.", "credit": "— Fotosúwret hám óńlew", "altBefore": "Andromeda galaktikasınıń FITS kórinisi", "altAfter": "Andromeda galaktikasınıń tayar súwreti"};
  const english={altBefore:'Display-stretched FITS preview of the same field',altAfter:'Finished Andromeda photograph'};
  document.querySelectorAll('[data-t]').forEach(el=>english[el.dataset.t]=el.textContent);
  function cyrl(text){const m={a:'а',á:'ә',b:'б',d:'д',e:'е',f:'ф',g:'г',ǵ:'ғ',h:'ҳ',x:'х',ı:'ы',i:'и',j:'ж',k:'к',q:'қ',l:'л',m:'м',n:'н',ń:'ң',o:'о',ó:'ө',p:'п',r:'р',s:'с',t:'т',u:'у',ú:'ү',v:'в',w:'ў',y:'й',z:'з',c:'ц'};return text.split(/(FITS|JPEG|William Optics UltraCat 56|ZWO ASI2600MC AIR|Askar Colour Magic D1|D2)/g).map(p=>/^(FITS|JPEG|William Optics UltraCat 56|ZWO ASI2600MC AIR|Askar Colour Magic D1|D2)$/.test(p)?p:p.replace(/sh|ch|[a-záǵıńóú]/gi,ch=>{const l=ch.toLowerCase(),r=l==='sh'?'ш':l==='ch'?'ч':m[l]||ch;return ch[0]===ch[0].toUpperCase()?r.toUpperCase():r;})).join('');}
  const select=document.getElementById('language');
  function apply(){const language=select.value;document.documentElement.lang=language;const t=k=>language==='en'?english[k]:language==='kaa-Latn'?latin[k]:cyrl(latin[k]);document.querySelectorAll('[data-t]').forEach(el=>el.textContent=t(el.dataset.t));document.getElementById('before-image').alt=t('altBefore');document.getElementById('after-image').alt=t('altAfter');document.title=t('title')+' — QARA TUYNIK';try{localStorage.setItem('qara-language',language);}catch{}}
  try{const saved=localStorage.getItem('qara-language');if(['en','kaa-Latn','kaa-Cyrl'].includes(saved))select.value=saved;}catch{}
  select.addEventListener('change',apply);apply();
  const slider=document.getElementById('reveal');slider.addEventListener('input',()=>{document.getElementById('compare').style.setProperty('--split',slider.value+'%');document.getElementById('amount').value=slider.value+'%';});
})();
