(() => {
 'use strict';
 const $=id=>document.getElementById(id);
 const photos=[['andromeda','Andromeda Galaxy','Andromeda galaktikası','Андромеда галактикасы'],['heart-and-soul','Heart & Soul Nebulae','Júrek hám Jan tumanlıqları','Жүрек ҳәм Жан туманлықлары'],['orion','Orion Nebula','Orion tumanlıǵı','Орион туманлығы'],['veil','Veil Nebula','Perde tumanlıǵı','Перде туманлығы'],['elephant-trunk','Elephant’s Trunk region','Pil tumsıǵı aymaǵı','Пил тумсығы аймағы'],['north-america','North America Nebula','Arqa Amerika tumanlıǵı','Арқа Америка туманлығы']];
 const words={exit:['← Exit','← Shıǵıw','← Шығыў'],welcome:['Watch the sky','Aspandı tamashalań','Аспанды тамашалаң'],note:['Six photographs. A quiet journey. Music is optional.','Altı súwret. Tınısh sayaxat. Muzıkanı qálewińizshe qosıń.','Алты сүўрет. Тыныш саяхат. Музыканы қәлеўиңизше қосың.'],start:['Start the journey','Sayaxattı baslaw','Саяхатты баслаў'],previous:['Previous','Aldınǵı','Алдыңғы'],next:['Next','Keyingi','Кейинги'],pause:['Pause','Toqtatıw','Тоқтатыў'],play:['Play','Dawam ettiriw','Даўам еттириў'],on:['Music on','Muzıka qosılǵan','Музыка қосылған'],off:['Music off','Muzıka óshirilgen','Музыка өширилген'],volume:['Volume','Dawıs kúshi','Даўыс күши'],full:['Fullscreen','Tolıq ekran','Толық экран'],window:['Exit fullscreen','Tolıq ekrannan shıǵıw','Толық экраннан шығыў'],hint:['12 seconds per photograph · Arrow keys to browse · Space to pause · Escape to exit','Hár súwret 12 sekund · Baǵdar túymeleri: súwretler · Boslıq: toqtatıw · Escape: shıǵıw','Ҳәр сүўрет 12 секунд · Бағдар түймелери: сүўретлер · Бослық: тоқтатыў · Escape: шығыў'],imageError:['This photograph could not load. Try Next.','Súwret júklenbedi. Keyingi túymesin basıń.','Сүўрет жүкленбеди. Кейинги түймесин басың.'],audioError:['Music could not start. Please try again.','Muzıka qosılmadı. Qaytadan urınıń.','Музыка қосылмады. Қайтадан урының.'],fullError:['Fullscreen is unavailable; the cinema still fills this page.','Tolıq ekran qoljetimsiz; kórsetilim usı bette dawam etedi.','Толық экран қолжетимсиз; көрсетилим усы бетте даўам етеди.']};
 let lang=0,index=0,layer=0,started=false,playing=false,timer=null,remaining=12000,deadline=0,error='';
 const frames=[$('frame-a'),$('frame-b')],reduced=matchMedia('(prefers-reduced-motion: reduce)');
 const t=k=>words[k][lang];
 function labels(){for(const [id,key]of Object.entries({exit:'exit','welcome-title':'welcome','welcome-note':'note',start:'start',previous:'previous',next:'next','volume-label':'volume',hint:'hint'}))$(id).textContent=t(key);$('pause').textContent=t(playing?'pause':'play');$('pause').setAttribute('aria-pressed',String(!playing));$('music').textContent=t(musicOn?'on':'off');$('music').setAttribute('aria-pressed',String(musicOn));$('fullscreen').textContent=t(document.fullscreenElement?'window':'full');$('title').textContent=photos[index][lang+1];frames[layer].alt=photos[index][lang+1];$('status').textContent=error?t(error):'';document.title=t('welcome')+' — QARA TUYNIK';}
 function schedule(){clearTimeout(timer);if(playing){deadline=performance.now()+remaining;timer=setTimeout(()=>{remaining=12000;show(index+1);},remaining);}}
 function setPlaying(value){if(playing&&!value)remaining=Math.max(0,deadline-performance.now());playing=value;$('cinema').classList.toggle('running',playing);if(playing)schedule();else clearTimeout(timer);labels();}
 function show(next){index=(next+photos.length)%photos.length;remaining=12000;error='';const old=frames[layer];old.classList.remove('visible');old.setAttribute('aria-hidden','true');layer=1-layer;const image=frames[layer];image.style.animation='none';void image.offsetWidth;image.style.animation='';image.onload=()=>{if(image===frames[layer]){error='';labels();}};image.onerror=()=>{if(image===frames[layer]){error='imageError';labels();}};image.src='assets/gallery/'+photos[index][0]+'.jpg';image.alt=photos[index][lang+1];image.removeAttribute('aria-hidden');image.classList.add('visible');$('count').textContent=String(index+1).padStart(2,'0')+' / 06';labels();schedule();}
 // An original, quiet synthesized pad; no external audio or movie soundtrack.
 let ctx=null,master=null,musicOn=false,nodes=[],musicTimer=null,chord=0;
 function stopMusic(){musicOn=false;clearTimeout(musicTimer);for(const n of nodes){try{n.stop();}catch{}n.disconnect();}nodes=[];if(master&&ctx)master.gain.setValueAtTime(0,ctx.currentTime);if(ctx)ctx.suspend().catch(()=>{});labels();}
 function playChord(){if(!musicOn)return;const notes=[[45,52,57,64],[41,48,57,60],[48,55,60,64],[43,50,57,62]][chord++%4],now=ctx.currentTime;for(const note of notes){const osc=ctx.createOscillator(),gain=ctx.createGain();osc.type='sine';osc.frequency.value=440*Math.pow(2,(note-69)/12);gain.gain.setValueAtTime(0,now);gain.gain.linearRampToValueAtTime(.045,now+2);gain.gain.linearRampToValueAtTime(0,now+10);osc.connect(gain);gain.connect(master);nodes.push(osc);osc.onended=()=>{osc.disconnect();gain.disconnect();nodes=nodes.filter(n=>n!==osc);};osc.start(now);osc.stop(now+10.1);}musicTimer=setTimeout(playChord,8000);}
 $('music').addEventListener('click',async()=>{if(musicOn){stopMusic();return;}$('music').disabled=true;try{if(!ctx){const Audio=window.AudioContext||window.webkitAudioContext;ctx=new Audio();master=ctx.createGain();master.gain.value=0;const compressor=ctx.createDynamicsCompressor();master.connect(compressor);compressor.connect(ctx.destination);}await ctx.resume();if(document.hidden)return;musicOn=true;master.gain.setTargetAtTime(Number($('volume').value)/100,ctx.currentTime,.2);error='';playChord();labels();}catch{stopMusic();error='audioError';labels();}finally{$('music').disabled=false;}});
 $('volume').addEventListener('input',()=>{if(master&&musicOn)master.gain.setTargetAtTime(Number($('volume').value)/100,ctx.currentTime,.1);});
 $('start').addEventListener('click',()=>{started=true;$('welcome').hidden=true;$('pause').disabled=false;remaining=12000;setPlaying(true);$('pause').focus();});
 $('pause').addEventListener('click',()=>setPlaying(!playing));$('previous').addEventListener('click',()=>show(index-1));$('next').addEventListener('click',()=>show(index+1));
 $('fullscreen').hidden=!$('cinema').requestFullscreen;
 $('fullscreen').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await $('cinema').requestFullscreen();}catch{error='fullError';labels();}});document.addEventListener('fullscreenchange',labels);
 document.addEventListener('keydown',e=>{if(e.target.closest('input,select'))return;if(e.key==='ArrowRight'){e.preventDefault();show(index+1);}if(e.key==='ArrowLeft'){e.preventDefault();show(index-1);}if(e.code==='Space'&&started&&!e.target.closest('button,a')){e.preventDefault();setPlaying(!playing);}});
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!document.fullscreenElement){stopMusic();location.href='index.html#gallery';}});
 document.addEventListener('visibilitychange',()=>{if(document.hidden){setPlaying(false);stopMusic();}});window.addEventListener('pagehide',()=>{clearTimeout(timer);stopMusic();});$('exit').addEventListener('click',stopMusic);
 function language(){lang=['en','kaa-Latn','kaa-Cyrl'].indexOf($('language').value);if(lang<0)lang=0;document.documentElement.lang=$('language').value;try{localStorage.setItem('qara-language',$('language').value);}catch{}labels();}
 try{const saved=localStorage.getItem('qara-language');if(['en','kaa-Latn','kaa-Cyrl'].includes(saved))$('language').value=saved;}catch{}
 $('language').addEventListener('change',language);language();show(0);
})();
