(() => {
'use strict';
const $=id=>document.getElementById(id), data=window.QARA_COLLECTION;
const labels={all:['All','Hámmesi'],nebulae:['Nebulae','Tumanlıqlar'],galaxies:['Galaxies','Galaktikalar'],solar:['Moon & Planets','Ay hám planetalar'],films:['Films','Filmler'],clusters:['Star Clusters','Juldız toplamları'],behind:['Behind the Telescope','Teleskop artında']};
const latin={home:'Bas bet',eyebrow:'TELESKOPIM ARQALI',title:'Jıynalǵan jaqtılıq.',lead:'Tınısh túnlerdiń jeke atlası. Bultlardı, alıs galaktikalardı hám hár súwrettiń artındaǵı sáwleli waqıtlardı izertleń.',stats:'57 súwret · 4 film · I. Urazov',explore:'Izertlewdi baslań ↓',search:'Toplamnan izlew',empty:'Sáykes súwret tabılmadı. Basqa atama yamasa filtrdi tańlań.',footer:'I. Urazov tárepinen túsirilgen hám jıynalǵan. Nókisten juldızlarǵa.',volume:'Dawıs',close:'Jabıw ✕',version:'Nusqa',compare:'Nusqalardı salıstırıw',full:'Tolıq súwretti ashıw ↗',slider:'Salıstırıw ushın jıljıtıń',previous:'← Aldıńǵı',next:'Keyingi →'};
const english={};document.querySelectorAll('[data-t]').forEach(e=>english[e.dataset.t]=e.textContent);
function cyrl(s){const m={a:'а',á:'ә',b:'б',d:'д',e:'е',f:'ф',g:'г',ǵ:'ғ',h:'ҳ',x:'х',ı:'ы',i:'и',j:'ж',k:'к',q:'қ',l:'л',m:'м',n:'н',ń:'ң',o:'о',ó:'ө',p:'п',r:'р',s:'с',t:'т',u:'у',ú:'ү',v:'в',w:'ў',y:'й',z:'з',c:'ц'};return s.replace(/sh|ch|[a-záǵıńóú]/gi,c=>{const v=c.toLowerCase(),r=v==='sh'?'ш':v==='ch'?'ч':m[v]||c;return c[0]===c[0].toUpperCase()?r.toUpperCase():r;});}
let lang='en';try{lang=localStorage.getItem('qara-language')||'en';}catch{}if(!['en','kaa-Latn','kaa-Cyrl'].includes(lang))lang='en';$('language').value=lang;
const tr=(en,lat)=>lang==='en'?en:lang==='kaa-Cyrl'?cyrl(lat):lat;
let filter='all',shown=[],active=null,versionIndex=0,comparison=false,opener=null;
function category(key){return tr(...labels[key]);}
function renderFilters(){const box=$('filters');box.replaceChildren();for(const key of Object.keys(labels)){const b=document.createElement('button');b.type='button';b.textContent=category(key);b.setAttribute('aria-pressed',String(filter===key));b.onclick=()=>{filter=key;renderFilters();render();};box.append(b);}}
function render(){const query=$('search').value.trim().toLowerCase();shown=data.filter(g=>(filter==='all'||g.category===filter)&&[g.title,...g.versions.map(v=>v.original)].join(' ').toLowerCase().includes(query));const grid=$('collection-grid');grid.replaceChildren();for(const g of shown){const v=g.versions[0],b=document.createElement('button');b.type='button';b.className='card';const thumb=document.createElement('div');thumb.className='thumb';const im=document.createElement('img');im.src=v.thumb;im.alt=g.title;im.loading='lazy';im.decoding='async';im.width=v.width;im.height=v.height;thumb.append(im);if(g.versions.length>1||v.video){const badge=document.createElement('span');badge.className='badge';badge.textContent=v.video?'▶ '+Math.floor(v.duration/60)+':'+String(v.duration%60).padStart(2,'0'):g.versions.length+' '+tr('versions','nusqa');thumb.append(badge);}const h=document.createElement('h2');h.textContent=g.title;const p=document.createElement('p');p.textContent=category(g.category);b.append(thumb,h,p);b.onclick=()=>open(g,b);grid.append(b);}const count=shown.reduce((n,g)=>n+g.versions.length,0);$('result-count').textContent=shown.length+' '+tr('entries','bólim')+' · '+count+' '+tr('photographs & films','súwret hám film');$('empty').hidden=shown.length>0;}
function stopVideo(){const v=$('media-stage').querySelector('video');if(v){v.pause();v.removeAttribute('src');v.load();}}
function open(g,button){stopVideo();active=g;versionIndex=0;comparison=false;if(button)opener=button;updateViewer();if(!$('viewer').open){$('viewer').showModal();document.body.classList.add('modal-open');}const url=new URL(location.href);url.searchParams.set('target',g.slug);history.replaceState(null,'',url);}
function updateViewer(){stopVideo();const v=active.versions[versionIndex];$('viewer-title').textContent=active.title;$('viewer-category').textContent=category(active.category);$('original-name').textContent=tr('Source file: ','Derek faylı: ')+v.original;$('viewer-note').textContent=active.slug==='nebula-study'?tr('File labelled M57_GraXpert; target identification to be confirmed.','Fayl ataması M57_GraXpert; nısana atamasın anıqlaw kerek.'):v.video?tr('Play with the film’s own sound. Background music pauses during playback.','Filmniń óz dawısı menen tamashalań. Fon muzıkası toqtaydı.'):tr('Photograph by I. Urazov. Capture settings were not supplied for this file.','I. Urazov súwreti. Bul fayl ushın túsiriw parametrleri berilmegen.');
const sel=$('version');sel.replaceChildren();active.versions.forEach((x,i)=>{const o=document.createElement('option');o.value=i;o.textContent=(i+1)+' · '+x.original;sel.append(o);});sel.value=versionIndex;sel.disabled=active.versions.length<2;$('full-image').href=v.src;$('full-image').hidden=!!v.video;$('compare-toggle').hidden=!active.compare;$('compare-toggle').setAttribute('aria-pressed',String(comparison));$('comparison-control').hidden=!comparison;$('media-status').textContent='';const stage=$('media-stage');stage.replaceChildren();
if(comparison){const [a,b]=active.compare.map(id=>active.versions.find(x=>x.id===id));const box=document.createElement('div');box.className='compare-stage';box.style.aspectRatio=a.width+'/'+a.height;const back=document.createElement('img');back.src=b.src;back.alt=b.original;const front=document.createElement('img');front.src=a.src;front.alt=a.original;front.className='top';const divider=document.createElement('span');divider.className='divider';box.append(back,front,divider);stage.append(box);$('compare-left').textContent=a.original;$('compare-right').textContent=b.original;$('comparison').value=50;
}else if(v.video){const poster=document.createElement('img');poster.src=v.src;poster.alt=active.title;stage.append(poster);const overlay=document.createElement('div');overlay.className='play-overlay';const play=document.createElement('button');play.type='button';play.textContent='▶';play.setAttribute('aria-label',tr('Play film with sound','Filmdi dawısı menen qoyıw'));play.onclick=()=>{window.qaraMusic?.pause();const film=document.createElement('video');film.controls=true;film.playsInline=true;film.preload='none';film.poster=v.src;film.src=v.video;film.setAttribute('aria-label',active.title);film.addEventListener('play',()=>window.qaraMusic?.pause());film.addEventListener('error',()=>{$('media-status').textContent=tr('The film could not load. Please try again.','Film ashılmadı. Qayta urınıp kóriń.');});stage.replaceChildren(film);film.play().catch(()=>{$('media-status').textContent=tr('Press play in the video controls to begin.','Baslaw ushın video basqarıwındaǵı play túymesin basıń.');});};overlay.append(play);stage.append(overlay);
}else{const im=document.createElement('img');im.src=v.src;im.alt=active.title+' · '+v.original;im.onerror=()=>{$('media-status').textContent=tr('Image unavailable. Please reload.','Súwret ashılmadı. Qayta júkleń.');};stage.append(im);}}
function applyLanguage(){lang=$('language').value;document.documentElement.lang=lang;document.querySelectorAll('[data-t]').forEach(e=>e.textContent=tr(english[e.dataset.t],latin[e.dataset.t]));$('search').placeholder=tr('Search a target…','Nısananı izlew…');try{localStorage.setItem('qara-language',lang);}catch{}renderFilters();render();if(active&&$('viewer').open)updateViewer();document.dispatchEvent(new Event('qara-language-change'));}
$('language').addEventListener('change',applyLanguage);$('search').addEventListener('input',render);$('version').addEventListener('change',()=>{versionIndex=Number($('version').value);comparison=false;updateViewer();});$('compare-toggle').onclick=()=>{comparison=!comparison;updateViewer();};$('comparison').addEventListener('input',()=>{const value=$('comparison').value;const top=$('media-stage').querySelector('.top'),line=$('media-stage').querySelector('.divider');if(top)top.style.clipPath=`inset(0 ${100-value}% 0 0)`;if(line)line.style.left=value+'%';});
$('close').onclick=()=>$('viewer').close();$('viewer').addEventListener('close',()=>{stopVideo();document.body.classList.remove('modal-open');const url=new URL(location.href);url.searchParams.delete('target');history.replaceState(null,'',url);opener?.focus();});
function move(delta){if(!shown.length)return;const i=shown.indexOf(active);open(shown[(i+delta+shown.length)%shown.length]);}
$('previous').onclick=()=>move(-1);$('next').onclick=()=>move(1);$('viewer').addEventListener('keydown',e=>{if(e.target.matches('input,select,video'))return;if(e.key==='ArrowRight'){e.preventDefault();move(1);}if(e.key==='ArrowLeft'){e.preventDefault();move(-1);}});document.addEventListener('visibilitychange',()=>{if(document.hidden)$('media-stage').querySelector('video')?.pause();});applyLanguage();const wanted=new URL(location.href).searchParams.get('target');if(wanted){const g=data.find(x=>x.slug===wanted);if(g)open(g);}
})();
