(() => {
  'use strict';
  const latin={"series": "Súwret tariyxı · 05", "title": "Cygnus Loop", "lead": "Bir tumanlıq, eki reń nusqası. Jasıl hám kók TIFF nusqasın altın hám kók galeriyalıq súwret penen salıstırıń.", "before": "TIFF nusqası", "after": "Galeriya nusqası", "slider": "Óńlew nátiyjelerin salıstırıw", "help": "Hár bir nusqanı kóriw ushın jıljıtqıshtı yamasa baǵdar túymelerin paydalanıń.", "caption": "Shepte — usınılǵan TIFF faylınıń web nusqası. Ońda — galeriyadaǵı súwret. Eki súwret te óńlengen, ekewinde de juldızlar kórinedi.", "open": "Galeriya nusqasın ashıw", "openBefore": "TIFF nusqasın ashıw", "capture": "Súwret haqqında", "heading": "Cygnus Loop reńlerin izertlew.", "story": "Cygnus Loop súwretimniń eki reń nusqasındaǵı birdey juldızlar hám bultlardı salıstırıń.", "process": "TIFF galeriya súwretine sáykes burıldı. Jasıl hám kók reńleri saqlandı, qosımsha jarqınlıq sozıwı qollanılmadı.", "learning": "Úyreniwden bir estelik: reń hám kontrast súwrettiń tásirin qalay ózgertedi.", "credit": "— Fotosúwret hám óńlew", "altBefore": "Cygnus Loop TIFF nusqası", "altAfter": "Cygnus Loop galeriya nusqası"};
  const english={altBefore:'Web preview of supplied Cygnus Loop TIFF',altAfter:'Cygnus Loop gallery edit'};
  document.querySelectorAll('[data-t]').forEach(el=>english[el.dataset.t]=el.textContent);
  function cyrl(text){const m={a:'а',á:'ә',b:'б',d:'д',e:'е',f:'ф',g:'г',ǵ:'ғ',h:'ҳ',x:'х',ı:'ы',i:'и',j:'ж',k:'к',q:'қ',l:'л',m:'м',n:'н',ń:'ң',o:'о',ó:'ө',p:'п',r:'р',s:'с',t:'т',u:'у',ú:'ү',v:'в',w:'ў',y:'й',z:'з',c:'ц'};return text.split(/(FITS|TIFF|JPEG|William Optics UltraCat 56|ZWO ASI2600MC AIR|Askar Colour Magic D1|D2)/g).map(p=>/^(FITS|TIFF|JPEG|William Optics UltraCat 56|ZWO ASI2600MC AIR|Askar Colour Magic D1|D2)$/.test(p)?p:p.replace(/sh|ch|[a-záǵıńóú]/gi,ch=>{const l=ch.toLowerCase(),r=l==='sh'?'ш':l==='ch'?'ч':m[l]||ch;return ch[0]===ch[0].toUpperCase()?r.toUpperCase():r;})).join('');}
  const select=document.getElementById('language');
  function apply(){const language=select.value;document.documentElement.lang=language;const t=k=>language==='en'?english[k]:language==='kaa-Latn'?latin[k]:cyrl(latin[k]);document.querySelectorAll('[data-t]').forEach(el=>el.textContent=t(el.dataset.t));document.getElementById('before-image').alt=t('altBefore');document.getElementById('after-image').alt=t('altAfter');document.title=t('title')+' — QARA TUYNIK';try{localStorage.setItem('qara-language',language);}catch{}}
  try{const saved=localStorage.getItem('qara-language');if(['en','kaa-Latn','kaa-Cyrl'].includes(saved))select.value=saved;}catch{}
  select.addEventListener('change',apply);apply();
  const slider=document.getElementById('reveal');slider.addEventListener('input',()=>{document.getElementById('compare').style.setProperty('--split',slider.value+'%');document.getElementById('amount').value=slider.value+'%';});
})();
