(() => {
 'use strict';
 const names=['William Optics UltraCat 56','ZWO AM5','ZWO ASI2600MC AIR','ZWO EAF Pro','ZWO ASIAIR Plus'];
 const english={photo:"William Optics telescope and ZWO equipment in Islam's garden",equipment:'Equipment',r0:'01 / TELESCOPE',r1:'02 / TRACKING MOUNT',r2:'03 / IMAGING + GUIDING',r3:'04 / ELECTRONIC FOCUS',r4:'05 / DEW-HEATER TEST',d0:'The telescope at the heart of this setup. It collects the light used to create the photographs.',d1:'The mount supports the telescope and tracks the apparent movement of the sky during an exposure.',d2:'The imaging camera records the photographs. Its integrated guide camera is used for guiding, without a separate guide camera in this setup.',d3:'A motorised focuser used to make fine, repeatable focus adjustments.',d4:'In this photograph, the ASIAIR Plus was being tested as a power source for dew heating, as described by Islam. This is an experimental use, not a recommended wiring guide.'};
 const latin={eyebrow:'Súwretlerdiń artında',title:'Teleskop artında.',intro:'Baǵdaǵı úskenelerden alıstaǵı jaqtılıq bultlarına shekem. Súwrettegi hár bir bólekti tańlap, onıń wazıypası menen tanısıń.',instruction:'Súwrettegi nomerdi yamasa tómendegi úskeneni tańlań. Bul — súwrette kórsetilgen úskeneler, házirgi úskeneler dizimi emes.',test:'ASIAIR Plus: fotograf onı shıq jılıtqıshın elektr menen támiyinlew ushın sınap kórgen. Ol jılıtqıshtıń ózi emes. Bul jerde elektr jalǵaw usılı usınılmaydı.',lightTitle:'Jaqtılıqtı jıynaw',light:'Teleskop jaqtılıqtı jıynap, kamera jazıp alatuǵın súwretti payda etedi.',steadyTitle:'Dál baqlaw',steady:'Montirovka aspannıń kórinetuǵın háreketin baqlaydı. Gidlew uzaq ekspoziciyada baqlaw qátelerin dúzetiwge járdem beredi.',focusTitle:'Fokustı anıqlaw',focus:'Elektron fokuslawshı teleskoptıń fokusın dál ózgertedi.',gallery:'Fotosúwretlerdi kóriw →',photo:'Islamnıń baǵındaǵı William Optics teleskobı hám ZWO úskeneleri',equipment:'Úskeneler',r0:'01 / TELESKOP',r1:'02 / MONTIROVKA',r2:'03 / SÚWRETKE TÚSIRIW HÁM GIDLEW',r3:'04 / ELEKTRON FOKUSLAW',r4:'05 / SHÍQ JÍLÍTQÍSHÍN SÍNAW',d0:'Bul úskenelerdiń tiykarǵı bólegi — teleskop. Ol fotosúwretlerdi jaratıw ushın jaqtılıqtı jıynaydı.',d1:'Montirovka teleskoptı uslap turadı hám ekspoziciya waqtında aspannıń kórinetuǵın háreketin baqlaydı.',d2:'Tiykarǵı kamera fotosúwretlerdi jazıp aladı. Onıń ishine ornatılǵan gid kamerasi gidlew ushın qollanıladı, bul úskenede bólek gid kamerasi joq.',d3:'Fokustı dál hám qaytalanatuǵın túrde ózgertiw ushın qollanılatuǵın motorlı fokuslawshı.',d4:'Islamnıń aytıwınsha, bul súwrette ASIAIR Plus shıq jılıtqıshın elektr menen támiyinlew ushın sınalǵan. Bul — tájiriybe, elektr jalǵaw boyınsha usınıs emes.'};
 document.querySelectorAll('[data-t]').forEach(el=>english[el.dataset.t]=el.textContent);
 function cyrl(text){const m={a:'а',á:'ә',b:'б',d:'д',e:'е',f:'ф',g:'г',ǵ:'ғ',h:'ҳ',x:'х',ı:'ы',i:'и',j:'ж',k:'к',q:'қ',l:'л',m:'м',n:'н',ń:'ң',o:'о',ó:'ө',p:'п',r:'р',s:'с',t:'т',u:'у',ú:'ү',v:'в',w:'ў',y:'й',z:'з',c:'ц'};return text.split(/(ASIAIR Plus|William Optics|ZWO)/g).map(p=>/^(ASIAIR Plus|William Optics|ZWO)$/.test(p)?p:p.replace(/sh|ch|[a-záǵıńóú]/gi,ch=>{const l=ch.toLowerCase(),r=l==='sh'?'ш':l==='ch'?'ч':m[l]||ch;return ch[0]===ch[0].toUpperCase()?r.toUpperCase():r;})).join('');}
 const select=document.getElementById('language');let selected=0;
 names.forEach((name,i)=>{const b=document.createElement('button');b.type='button';b.dataset.part=i;b.textContent=(i+1)+' · '+name;b.setAttribute('aria-controls','component');document.getElementById('component-list').append(b);});
 function t(key){return select.value==='en'?english[key]:select.value==='kaa-Latn'?latin[key]:cyrl(latin[key]);}
 function show(){document.getElementById('component-title').textContent=names[selected];document.getElementById('component-role').textContent=t('r'+selected);document.getElementById('component-description').textContent=t('d'+selected);document.querySelectorAll('[data-part]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.part)===selected)));}
 function apply(){document.documentElement.lang=select.value;document.querySelectorAll('[data-t]').forEach(el=>el.textContent=t(el.dataset.t));document.getElementById('setup-photo').alt=t('photo');document.getElementById('component-list').setAttribute('aria-label',t('equipment'));document.title=t('title')+' — QARA TUYNIK';show();try{localStorage.setItem('qara-language',select.value);}catch{}}
 document.querySelectorAll('[data-part]').forEach(b=>b.addEventListener('click',()=>{selected=Number(b.dataset.part);show();}));
 try{const stored=localStorage.getItem('qara-language');if(['en','kaa-Latn','kaa-Cyrl'].includes(stored))select.value=stored;}catch{}
 select.addEventListener('change',apply);apply();
})();
