(() => {
  'use strict';
  const latin={series:'Súwret tariyxı · 01',title:'Júrek hám Jan',lead:'Bir juldızlar maydanı. Eki jarqıraǵan bult. FITS kórinisinen tayar súwretke shekemgi ózgeristi kóriń.',before:'FITS kórinisi',after:'Tayar súwret',slider:'Óńlew nátiyjelerin salıstırıw',help:'Hár bir nusqanı kóriw ushın jıljıtqıshtı yamasa baǵdar túymelerin paydalanıń.',caption:'Ázzi detallardı kórsetiw ushın FITS kórinisiniń jarqınlıǵı sozılǵan. Bul kameradan alınǵan óńlenbegen kadr emes, al óńlewdiń aldınǵı basqıshı. Tayar súwret — fotograf usınǵan JPEG faylı.',open:'Tayar súwretti ashıw',openBefore:'FITS kórinisin ashıw',capture:'Súwretke túsiriw',heading:'Jaqtılıqtı jıynaw.',story:'Islam Urazov William Optics UltraCat 56 teleskobı hám ZWO ASI2600MC AIR kamerası menen súwretke túsirgen. Bul súwret ushın Askar Colour Magic D1 hám D2 filtrleri qollanılǵan.',process:'FITS kórinisiniń báseń reńlerin tayar súwrettegi jıllı altın hám suwıq reńler menen salıstırıń. Eki kóriniste de bir juldızlar maydanı súwretlengen.',scope:'Teleskop',camera:'Kamera',filters:'Filtrler',sub:'Bir kadr ekspoziciyası',total:'Ulıwma ekspoziciya',pending:'Anıqlastırıladı',credit:'— Fotosúwret hám óńlew',altBefore:'Júrek hám Jan tumanlıqlarınıń FITS kórinisi',altAfter:'Júrek hám Jan tumanlıqlarınıń tayar súwreti'};
  const english={altBefore:'Display-stretched FITS preview of the same field',altAfter:'Finished Heart and Soul Nebulae photograph'};
  document.querySelectorAll('[data-t]').forEach(el=>english[el.dataset.t]=el.textContent);
  function cyrl(text){const m={a:'а',á:'ә',b:'б',d:'д',e:'е',f:'ф',g:'г',ǵ:'ғ',h:'ҳ',x:'х',ı:'ы',i:'и',j:'ж',k:'к',q:'қ',l:'л',m:'м',n:'н',ń:'ң',o:'о',ó:'ө',p:'п',r:'р',s:'с',t:'т',u:'у',ú:'ү',v:'в',w:'ў',y:'й',z:'з',c:'ц'};return text.split(/(FITS|JPEG|William Optics UltraCat 56|ZWO ASI2600MC AIR|Askar Colour Magic D1|D2)/g).map(p=>/^(FITS|JPEG|William Optics UltraCat 56|ZWO ASI2600MC AIR|Askar Colour Magic D1|D2)$/.test(p)?p:p.replace(/sh|ch|[a-záǵıńóú]/gi,ch=>{const l=ch.toLowerCase(),r=l==='sh'?'ш':l==='ch'?'ч':m[l]||ch;return ch[0]===ch[0].toUpperCase()?r.toUpperCase():r;})).join('');}
  const select=document.getElementById('language');
  function apply(){const language=select.value;document.documentElement.lang=language;const t=k=>language==='en'?english[k]:language==='kaa-Latn'?latin[k]:cyrl(latin[k]);document.querySelectorAll('[data-t]').forEach(el=>el.textContent=t(el.dataset.t));document.getElementById('before-image').alt=t('altBefore');document.getElementById('after-image').alt=t('altAfter');document.title=t('title')+' — QARA TUYNIK';try{localStorage.setItem('qara-language',language);}catch{}}
  try{const saved=localStorage.getItem('qara-language');if(['en','kaa-Latn','kaa-Cyrl'].includes(saved))select.value=saved;}catch{}
  select.addEventListener('change',apply);apply();
  const slider=document.getElementById('reveal');slider.addEventListener('input',()=>{document.getElementById('compare').style.setProperty('--split',slider.value+'%');document.getElementById('amount').value=slider.value+'%';});
})();
