(() => {
 'use strict';
 const latin={series:'Baqlaw kúndeligi · 01-jazba',title:'Kosmos reńlerin úyreniw.',lead:'SHO Hubble palitrasına sayaxatım: basqalardan úyreniw, óz súwretlerim menen islew hám reńler teńsalmaǵın tabıw.',date:'Kúndelik jazbası · 8 oktyabr 2026',type:'Óńlewdi úyreniw · Tumanlıq fotosúwreti',caption:'Meniń tayar reńli súwretim. Tolıq ólshemde kóriw ushın súwretti ashıń.',start:'Hár bir súwret penen úyreniw',p1:'YouTube meniń úyreniwimde úlken orın tutadı. Basqa astrofotograflardıń óńlew usılların túsindiriwin kóriw SHO Hubble palitrasın úyreniwime hám bul ideyalardı óz súwretlerimde qollanıwıma járdem berdi.',p2:'Men tiykarınan Siril menen, sonıń menen birge SETI Astro Suite Pro hám RC-Astro plaginleri menen isleymen. Aqırǵı ózgerisler ushın Affinity qollanaman. Bul qurallar súwretti ózim qálegen nátiyjege jetkeriw procesiniń bir bólegi.',lesson:'Úyrenip atırǵanım: SHO palitrası kúkirt, vodorod hám kislorod maǵlıwmatları arqalı tumanlıqtı basqasha kóriwge múmkinshilik beredi.',paletteTitle:'SHO neni ańlatadı?',paletteText:'Ádettegi SHO sáykesliginde kúkirt II qızılǵa, vodorod-alfa jasılǵa, kislorod III kók reńge sáykeslestiriledi. Bular — kórsetiw ushın tańlanǵan reńler; tumanlıq ápiwayı kózge bunday kórinbeydi.',s:'Kúkirt II → Qızıl',h:'Vodorod-alfa → Jasıl',o:'Kislorod III → Kók',paletteNote:'Bul palitra qaǵıydasın túsindiredi; usı súwret ushın qollanılǵan anıq kanal ajıratıw yamasa aralastırıw sazlamaların kórsetpeydi.',source:'NASA túsindirmesi: Hubble reńleri ↗',tools:'Meniń óńlew qurallarım',closing:'Bul kúndelik — súwretler menen birge úyrengenlerimdi bólisiw ornı: qollanatuǵın qurallarım, jańa ideyalar hám olardı ámelde qollanıwdan payda bolǵan súwretler.',motion:'Hárekettegi súwret',showcase:'Qısqa kórsetilim.',videoText:'Filmdi óziniń dawısı menen kóriń. Tayar bolǵanda oynatıw túymesin basıń; jaqınnan kóriw ushın tolıq ekrandı paydalanıń.',dateNote:'Joqarıdaǵı sáne — kúndelik jazbasınıń sánesi, súwretke túsirilgen sáne emes.',download:'Videonı júklep alıw',alt:'Kók hám altın reńli, qara shań dúzilisi bar tumanlıq súwreti',videoLabel:'Óz dawısı bar astrofotografiya kórsetilimi',error:'Video júklenbedi. Betti qayta júkleń yamasa video faylın tekseriń.'};
 const english={alt:'Nebula photograph in blue and gold with dark dust structures',videoLabel:'Astrophotography showcase with original audio',error:'The video could not load. Reload the page or check the video file.'};
 document.querySelectorAll('[data-t]').forEach(el=>english[el.dataset.t]=el.textContent);
 function cyrl(text){const m={a:'а',á:'ә',b:'б',d:'д',e:'е',f:'ф',g:'г',ǵ:'ғ',h:'ҳ',x:'х',ı:'ы',i:'и',j:'ж',k:'к',q:'қ',l:'л',m:'м',n:'н',ń:'ң',o:'о',ó:'ө',p:'п',r:'р',s:'с',t:'т',u:'у',ú:'ү',v:'в',w:'ў',y:'й',z:'з',c:'ц'};return text.split(/(SHO|Hubble|YouTube|Siril|SETI Astro Suite Pro|RC-Astro|Affinity|NASA|III|II)/g).map(p=>/^(SHO|Hubble|YouTube|Siril|SETI Astro Suite Pro|RC-Astro|Affinity|NASA|III|II)$/.test(p)?p:p.replace(/sh|ch|[a-záǵıńóú]/gi,ch=>{const l=ch.toLowerCase(),r=l==='sh'?'ш':l==='ch'?'ч':m[l]||ch;return ch[0]===ch[0].toUpperCase()?r.toUpperCase():r;})).join('');}
 const select=document.getElementById('language'),video=document.getElementById('showcase');let failed=false;
 function t(key){return select.value==='en'?english[key]:select.value==='kaa-Latn'?latin[key]:cyrl(latin[key]);}
 function apply(){document.documentElement.lang=select.value;document.querySelectorAll('[data-t]').forEach(el=>el.textContent=t(el.dataset.t));document.title=t('title')+' — QARA TUYNIK';document.getElementById('study-image').alt=t('alt');video.setAttribute('aria-label',t('videoLabel'));if(failed)document.getElementById('video-status').textContent=t('error');try{localStorage.setItem('qara-language',select.value);}catch{}}
 try{const saved=localStorage.getItem('qara-language');if(['en','kaa-Latn','kaa-Cyrl'].includes(saved))select.value=saved;}catch{}
 select.addEventListener('change',apply);apply();
 function reportError(){failed=true;document.getElementById('video-status').textContent=t('error');}
 video.addEventListener('error',reportError);video.querySelector('source').addEventListener('error',reportError);
 video.addEventListener('playing',()=>{failed=false;document.getElementById('video-status').textContent='';});
 document.addEventListener('visibilitychange',()=>{if(document.hidden)video.pause();});
 if('IntersectionObserver' in window)new IntersectionObserver(entries=>{if(!entries[0].isIntersecting)video.pause();}).observe(video);
})();
